### ISSUE TITLE
Cross Concept Changes: Force Survey Selections If >=6 Rating On Thermometer

### ISSUE THREAD

**Issue by RoboticMind** [kevinsullivan/concepts_exploration#15]
>6.  If a person rates =/>6, they should be forced to pick something.

ref: kevinsullivan/moralpain_dev/issues/145

**Comment by nehakrishnakumar** [comment]
This is also a good way to avoid spam and thus some sort of a security measure as well!

**Comment by RoboticMind** [comment]
This issue seems to be the same as #53, closing this issue in place of that one
